trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: XplatGenerateReleaseNotes@4
  inputs:
    outputfile: 'ReleaseNotes.md'
    templateLocation: 'InLine'
    inlinetemplate: |
      # Release Notes
            ## Commits
            {{#each commits}}
            - {{this.message}}
            {{/each}}
            ## Work Items
            {{#each workitems}}
            - {{this.id}} {{this.fields['System.Title']}}
            {{/each}}
    dumpPayloadToConsole: false
    dumpPayloadToFile: false
    replaceFile: True
    getParentsAndChildren: False
    getAllParents: False
    getIndirectPullRequests: False
    stopOnError: False
    considerPartiallySuccessfulReleases: False
    checkForManuallyLinkedWI: False
    wiqlFromTarget: 'WorkItems'



# 2️⃣ Publish the release notes as a build artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/ReleaseNotes.md'
    artifactName: 'ReleaseNotes'
  displayName: Publish Release Notes